[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 30
port = 1212
bindto = "::,0.0.0.0"
max_connections = 52

[ic]

flavor_text = true

[status]
# The status server is the TCP side, used by the launcher to determine engine version, etc.
# To be clear: Disabling it makes the launcher unable to connect!
enabled = true

[game]
hostname = "[RU][HRP][18+]КосмиКрафт"
desc = "Добро пожаловать на КосмиКрафт - игровой 18+ MRP+ сервер! \nНаша текущая сборка взята от ныне почившего сервера Lust Station, у нас много новых рас и ролей, а также дополнительная одежда. \nПрисоединяйся и играй с нами."
map_pool = "DefaultMapPool"
map_rotation = true
role_timers = true
lobbyenabled = true
soft_max_players = 40
maxplayers = 52

[rules]
time = 10.0

[queue]
enabled = true

[console]
loginlocal = true

[hub]
advertise = true
tags = "lang:ru,rp:hard,18+"
server_url = ""
hub_urls = "https://central.spacestation14.io/hub/"

[infolinks]
discord = "https://discord.gg/BvJUmcCK8z"
wiki = "https://station14.ru/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0"

[auth]
# 0 = Optional, 1 = Required, 2 = Disabled
mode = 1
# server = https://central.spacestation14.io/auth/

[shuttle]
grid_fill = true
auto_call_time = 120
emergency = true
arrivals = true

[admin]
see_own_notes = true
