- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterVestArmorMedSec
    back: ClothingBackpackBrigmedicFilled
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesColorBlack
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretSecurityMedic
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltBrigmedicSecurityWebbing
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
  underweart: ClothingUnderwearTopBraSportsAlternative # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerclothingskirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelBrigmedicFilled
  duffelbag: ClothingBackpackDuffelBrigmedicFilled
  
- type: entity
  name: РПС Бригмедика
  suffix: Filled
  id: ClothingBeltBrigmedicSecurityWebbing
  parent: ClothingBeltSecurityWebbing
  description: Уникальный, универсальный разгрузочный жилет с ремнями и поясом, может вмещать снаряжение службы безопасности.
  components:
  - type: StorageFill
    contents:
      - id: Brutepack
        amount: 2
      - id: Ointment
        amount: 1
      - id: Bloodpack
        amount: 1